### PR TITLE
Portfolio using HTML CSS and javascript 

### PR DESCRIPTION
**Pull request by Sumit24-prog**

### CODE REVIEW

**Comment by NitinShaily** [comment]
Hy Sumit, it seems like you have added a git repo instead of a project folder inside HTML CSS JAVASCRIPT try to delete .git file inside your folder since we can't review your code if it is a submodule/repo instead of a normal folder.

**Comment by Sumit24-prog** [comment]
Oo my mistake..

**Comment by Sumit24-prog** [comment]
Hey actually i see my folder but there is no ".git" file inside my repo ....can you tell me in detail...what happening....

**Comment by k40t1k-sys** [comment]
The folder name should contain your full name not the username.

**Comment by k40t1k-sys** [comment]
And it will be better if you can host the portfolio and provide the link for inspection.

**Comment by Sumit24-prog** [comment]
Okay

**Comment by Sumit24-prog** [comment]
https://sumit24-prog.github.io/SumitRawat.github.io/

**Comment by k40t1k-sys** [comment]
You have done a great work with the website but there is always chances of improvements. I hope you will not stop and keep updating it.

**Comment by Sumit24-prog** [comment]
Thanks

**Pull request merged**
