### PR TITLE
Tamanna-S added a game python/road_cross game by Tamanna-S

### PR DESCRIPTION
**Pull request by Tamanna-S**

### CODE REVIEW

**Comment by Sumit24-prog** [comment]
Please Provide Descriptions.

**Comment by Tamanna-S** [comment]
this is a road crossing game made in python with the use of turtle module.

**Comment by k40t1k-sys** [comment]
Sorry @Tamanna-S, but it looks like you have copied the code from @jhenilparihar and have not added any feature of your own. As I have run the game it looks like the program still have some bugs like there is no option to replay the game once a player loose. You can work on it and have some additional features of your. We will be waiting for the changes. Also if you try to use anybody else's code please give mention to them as well.

**Comment by Tamanna-S** [comment]
alright!
but i haven't copied it.

**Comment by jhenilparihar** [comment]
Thank You @k40t1k-sys for your support and suggest. I will definitely look up in my code and will add re-play option.

**Comment by jhenilparihar** [comment]
Hey i have added that option to replay the game once a player loose. You can check it out [here](https://github.com/jhenilparihar/turtle-crossing-game) and please let me know if there any any other bugs.

**Comment by Sumit24-prog** [comment]
jhenilparihar bro make a pull request we will review it .

**Pull request closed without merging**
