### PR TITLE
Uploaded My Files

### PR DESCRIPTION
**Pull request by YuvrajSHAD**
I Created this template for my Project. I think others should have the idea to create Template like this.
it Have multiple effects and transition and preload in JS

### CODE REVIEW

**Comment by YuvrajSHAD** [comment]
Please Review and Merge it!

**Comment by k40t1k-sys** [comment]
Please create a new PR in [this](https://github.com/deepakuniyaliit/open-source-projects) repository.

**Comment by YuvrajSHAD** [comment]
K

**Comment by YuvrajSHAD** [comment]
Done i have made my PR in Your Preferred Repo! 
Please Review it.

**Pull request closed without merging**
