### PR TITLE
Tamanna-S improved the road_cross game

### PR DESCRIPTION
**Pull request by tamannasgh**
what about it ?

### CODE REVIEW

**Comment by NitinShaily** [comment]
Hy Tamanna, can you add a readme in your project where you could briefly describe your project like what exactly it is doing along with a screenshot or a GIF demo. Refer to a project "Movie app" in HTMLCss directory here: [Movie app](https://github.com/deepakuniyaliit/hacktoberfest2021/tree/main/HTML%20CSS%20JavaScript) to see how you can contribute.

**Comment by Tamanna-S** [comment]
mujhe itna nhi aata mtlb gif kse add krna h aap poocho jo janna h main aise bta dungi😅

**Comment by Tamanna-S** [comment]
wse ye bss ek game h chhoti se turtle se bnai h python main

**Comment by NitinShaily** [comment]
no problem, do you know how to add a readme in your project? make a file name "readme.md" inside your project folder that describes a little bit about your project. Here's a link: [link](https://dev.to/rohit19060/how-to-write-stunning-github-readme-md-template-provided-5b09) if you want to learn how to make a good readme.

**Comment by Tamanna-S** [comment]
hey @NitinShaily i've tried many times but vs code and my photos also doesn't support the gif format what can i do ?

**Comment by NitinShaily** [comment]
Just add a readme file in it with a description of game don't add any GIF

**Comment by Tamanna-S** [comment]
done!
i added a commit (everything done) check it out

**Comment by NitinShaily** [comment]
ok nice finally you have done it and have learned something new ( ´･･)ﾉ(._.`)

**Comment by Tamanna-S** [comment]
seriosly!!
thank you verry verry much @NitinShaily

**Comment by NitinShaily** [comment]
no problem.. Have a good Octoberfest 😁

**Comment by Sumit24-prog** [comment]
Hello @Tamanna-S ,This repository is the old and Excluded From Hacktoberfest .So we are requesting you to please make a Pull Request in new Repository.
Here is the link
https://github.com/deepakuniyaliit/open-source-projects

**Comment by tamannasgh** [comment]
done! @Sumit24-prog

**Pull request merged**
